# Imagen base
FROM python:3.10-slim

WORKDIR /app

# Instalar dependencias
COPY /requirements.txt .
RUN pip install --no-cache-dir --default-timeout=300 -r requirements.txt

# Copiar el código fuente y configuración
COPY mlops_pipeline/src ./src
COPY mlops_pipeline/data ./data
COPY /config.json .

# Exponer puerto API
EXPOSE 8000

# Ejecutar la API
CMD ["uvicorn", "src.api_deploy:app", "--host", "0.0.0.0", "--port", "8000"]
