FROM python:3.10-slim
WORKDIR /app

COPY /requirements.txt .
RUN pip install --no-cache-dir --default-timeout=300 -r requirements.txt

COPY mlops_pipeline/src ./src
COPY mlops_pipeline/data ./data
COPY /config.json .

EXPOSE 8501
CMD ["streamlit", "run", "src/model_deploy.py", "--server.port=8501", "--server.address=0.0.0.0"]
